import fs from 'node:fs';
import path from 'node:path';
const root = import.meta.dirname;
const data = JSON.parse(fs.readFileSync(path.join(root, 'products.json'), 'utf8'));
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = value => value == null ? '확인 필요' : `${value.toLocaleString('ko-KR')}원`;
const link = (label, url, cls = '') => `<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`;
const statusText = {selected:'선택',proposed:'추천 후보',pending:'구매 보류',reserve:'예비 후보'};
const rice = data.items.find(x => x.id === 'rice');
const active = data.items.filter(x => x.include !== false);
const priced = active.filter(x => x.price != null);
const subtotal = priced.reduce((n,x) => n + x.price * x.qty, 0);
const unknown = active.filter(x => x.price == null);
const cards = data.items.map((x,i) => `<article id="${esc(x.id)}" class="card" data-category="${esc(x.category)}" data-status="${esc(x.status)}">
  <div class="media"><span class="rank">${String(i+1).padStart(2,'0')} · ${esc(x.brand)}</span><span class="badge ${esc(x.status)}">${statusText[x.status]}</span>
    ${x.image ? `<img src="${esc(x.image)}" alt="${esc(x.name)} ${esc(x.size)}" loading="lazy" width="600" height="450" referrerpolicy="no-referrer">` : ''}
    <div class="fallback" ${x.image?'hidden':''}><strong>${esc(x.size)}</strong><small>상품 사진은 구매처에서 확인</small></div>
  </div><div class="card-body"><p class="category">${esc(x.category)} · ${esc(x.role)}</p><h3>${esc(x.name)}</h3><p class="model">${esc(x.size)} · ${esc(x.qtyLabel)}</p>
  <div class="price-box"><span class="price-label">${esc(x.priceLabel || '확인 상품가')}</span><span class="price">${money(x.price)}${x.qty>1?` <small>× ${x.qty}</small>`:''}</span>
  <p class="price-note">${esc(x.priceNote || '')}${x.qty>1&&x.price!=null?` · 소계 ${money(x.price*x.qty)}`:''}</p><p class="price-note">${esc(x.shipping)}</p></div>
  <p class="reason">${esc(x.reason)}</p><ul class="specs">${x.specs.map(s=>`<li>${esc(s)}</li>`).join('')}</ul>${x.watch?`<p class="watch">${esc(x.watch)}</p>`:''}
  <div class="actions">${link(x.shopLabel || '1순위 · 쿠팡',x.url,'action primary')}${x.secondary?link(x.secondary.label,x.secondary.url,'action'):''}</div>
  <details class="evidence"><summary>가격·규격 확인 근거</summary><p>${esc(x.verification)}</p>${(x.sources||[]).map(s=>`<p>${link(s.label,s.url)}</p>`).join('')}</details></div></article>`).join('\n');
const rows = data.items.map(x=>`<tr><td><a href="#${esc(x.id)}">${esc(x.name)}</a><small>${esc(x.size)}${x.include===false?' · 합계 제외':''}</small></td><td>${esc(x.qtyLabel)}</td><td class="money">${money(x.price)}<small>${esc(x.priceLabel)}</small></td><td class="money">${x.include===false?esc(x.excludeReason || '보류'):money(x.price==null?null:x.price*x.qty)}</td></tr>`).join('\n');
const categories = [...new Set(data.items.map(x=>x.category))];
const html = `<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f2f0e8"><meta name="description" content="ZZEE 주방 위시리스트. 쿠팡 우선 구매 링크, 다이소 믹싱볼과 조리도구, 제품별 규격·수량·가격과 예산."><title>ZZEE’ KITCHEN — 주방 위시리스트</title><link rel="stylesheet" href="styles.css"><script src="app.js" defer></script></head>
<body><a class="skip" href="#list">구매 목록으로 바로가기</a><header class="topbar"><a class="brand" href="../index.html"><b>Z</b> ZZEE PROJECTS</a><span class="top-meta">PRICE CHECK · 2026.10.06 KST</span></header><main>
<section class="hero" aria-labelledby="page-title"><div><p class="eyebrow">EVERYDAY COOKING / 2–3 PEOPLE</p><h1 id="page-title">ZZEE’<span>KITCHEN</span></h1><p class="lead">매일 쓰는 2–3인 주방, 고기 1.2kg 프렙, 가끔 여럿이 먹는 한 끼.<br>고른 물건의 크기와 수량, 바로 살 곳과 가격을 한곳에.</p></div><aside class="hero-note"><strong>쿠팡 먼저, 공식몰 다음.</strong><p>1순위 쿠팡 · 2순위 네이버 브랜드 공식몰.<br>다이소 지정 품목은 다이소몰에서. 공식 스마트스토어의 정확한 상품을 확인하지 못한 경우 제조사 공식 페이지를 근거로 연결했습니다.</p><p><a href="#budget">수량별 가격표 보기</a></p></aside></section>
<section class="dashboard" aria-label="구매 목록 요약"><div class="metric"><span class="metric-label">구매 검토 품목</span><strong>${active.length}개</strong><small>열원 확인·예비 ${data.items.length-active.length}개 별도</small></div><div class="metric"><span class="metric-label">구매 계획 상품가</span><strong>${money(subtotal)}</strong><small>WOW 쿠폰 적용 표시가 포함</small></div><div class="metric"><span class="metric-label">다이소 26 + 30cm</span><strong>5,000원</strong><small>같은 제조사 · 볼 2개</small></div><div class="metric"><span class="metric-label">도자기 밥 용기</span><strong>총 ${rice.qty*4}개</strong><small>4개입 ${rice.qty}세트 · 계획 ${money(rice.price*rice.qty)}</small></div></section>
<p class="notice">2026.10.06 상품 화면 기준. <strong>WOW 가입 여부는 미확인</strong>이며 쿠폰·회원 배송 혜택은 조건부입니다. 카드할인과 적립금은 차감하지 않았습니다. 배송비는 <a href="#budget">예산표 아래</a>에 별도로 정리했습니다.</p>
<div class="controls-wrap"><div class="controls" aria-label="품목 필터"><button class="filter-button" type="button" data-filter="" aria-pressed="true">전체</button>${categories.map(c=>`<button class="filter-button" type="button" data-filter="${esc(c)}" aria-pressed="false">${esc(c)}</button>`).join('')}<label class="search"><span class="sr-only">제품명·브랜드 검색</span><input id="search" type="search" placeholder="제품명·브랜드·크기 검색"></label><label><span class="sr-only">선택 상태</span><select id="status"><option value="">전체 상태</option><option value="selected">선택</option><option value="proposed">추천 후보</option><option value="pending">구매 보류</option><option value="reserve">예비 후보</option></select></label><button class="reset" id="reset" type="button">초기화</button></div></div>
<div class="list-heading" id="list"><h2>주방 구매 목록</h2><span class="count" id="count" aria-live="polite">${data.items.length}개 품목</span></div><noscript><p>검색 기능은 JavaScript가 필요합니다. 아래 전체 목록과 가격은 그대로 확인할 수 있습니다.</p></noscript><section class="catalogue" aria-label="주방 제품">${cards}</section><p id="empty" class="empty" hidden>조건에 맞는 제품이 없습니다. 검색어나 필터를 초기화해 주세요.</p>
<section class="guide" aria-label="용도별 선택 메모"><article><h2>18 / 26 / 30cm, 역할을 나눠서.</h2><p><strong>리본제이 18cm·1.1L</strong>는 소량 재료 세척·계란·소스용 주력으로 괜찮습니다. 2–3인분 음식 전체를 한 번에 버무리는 볼로는 작을 수 있습니다. 3종은 볼·채반·트레이이며 트레이의 밀폐 성능은 확인되지 않았습니다.</p><p><strong>다이소 26cm</strong>는 중간 프렙용, <strong>30cm</strong>는 비빔밥·큰 무침용 추천입니다. 두 제품의 실제 L 용량·깊이는 미표기입니다. 고기 1.2kg에 채소까지 넣어 비빌 때는 30cm를 함께 활용하는 편이 여유롭습니다.</p></article><article><h2>도마와 보관통도 용도를 나눠서.</h2><p>이케아 28×22cm는 매일 소량 손질, 엔드그레인은 넓은 조리 공간, 비슷한 크기의 스텐 도마는 생고기·김치용으로 구분합니다.</p><p>500mL급 4개 + 1L급 2개, 대형은 2L 대신 2.4L 대안과 3L를 각 1개. 정확한 용량이나 재질이 요청과 다르면 제품 카드에 표시하며, 미확인 조건을 충족한 것으로 계산하지 않습니다.</p></article></section>
<section class="budget" id="budget"><h2>수량과 가격</h2><p class="budget-intro">필터와 관계없이 전체 구매 계획 기준입니다. 아래 소계는 표시된 조건부 상품가이며 최종 결제액이 아닙니다. 추천 후보와 밥 용기 12개를 포함하고 열원 확인 중인 이브라·예비 다소니는 제외했습니다.</p><div class="table-wrap"><table><caption class="sr-only">품목별 수량과 상품가 소계</caption><thead><tr><th>품목·규격</th><th>주문 수량</th><th class="money">기준 가격</th><th class="money">계획 소계</th></tr></thead><tbody>${rows}<tr class="total-row"><td colspan="3">구매 계획 상품가 (${priced.length}개 품목)</td><td class="money">${money(subtotal)}</td></tr></tbody></table></div>${data.budgetNotes.map(t=>`<p class="budget-intro">${esc(t)}</p>`).join('')}</section>
<details class="records"><summary>보유품·미정 품목과 조사 기록</summary><p>작은 스텐 냄비와 큰 스텐 냄비는 보유 중이며 중복 구매하지 않습니다. 이전 과도·빵칼·식사용 실리콘 젓가락·세라믹 도마·별도 30cm 채망은 이번 구매 합계에 넣지 않았습니다. 기존 기록은 아래에 보존했습니다.</p><div class="record-links"><a href="HANDOFF.md">최신 인수인계</a><a href="HISTORY-20261006.md">이전 조사 기록</a><a href="products.json" download>제품·가격 데이터</a></div><p>핸디 24cm 프라이팬의 소비자원 시험 결과를 28cm 웍의 시험 결과로 확대하지 않습니다. ‘선택’은 구매 완료가 아니라 사용자가 고른 조건입니다.</p><button class="button" id="copy" type="button">이어하기 문구 복사</button><p id="copy-result" role="status"></p><pre id="resume-prompt">ZZEE 주방 위시리스트를 이어줘. kitchen-setup/HANDOFF.md와 products.json을 먼저 읽고 최신 선택을 유지해. 구매처는 쿠팡 1순위, 네이버 브랜드 공식몰 2순위이며 다이소 지정품은 다이소몰을 사용해. 정확한 옵션·수량·WOW쿠폰·배송을 구분하고 확인되지 않은 가격은 합계에서 제외해. 이브라 18cm는 디자인 선호 제품이지만 인덕션 직접 사용 불가로 열원 확인 전 합계에서 제외해. 인덕션 플레이트와 손이야기는 제외했고 다소니는 예비 후보야. 다이소 스푼은 1044020 실리콘 미니 요리 스푼이며 계량스푼이 아니야. 도자기 밥 용기는 총12개,4개입3세트이며 쿠폰의 다중 수량 적용은 미확인이야. 구매는 실행하지 않았어.</pre></details></main><footer>ZZEE · 2026.10.06 · 상품 이미지는 각 판매처의 실제 제품 이미지입니다. 가격·재고·쿠폰은 변경될 수 있습니다. 구매 실행 없음.</footer></body></html>`;
fs.writeFileSync(path.join(root, 'index.html'), html);
console.log(JSON.stringify({cards:data.items.length,active:active.length,priced:priced.length,unknown:unknown.length,subtotal}));
